### ISSUE TITLE
Kojimaizer sometimes cuts a multi-byte character in half, corrupting it

### ISSUE THREAD

**Issue by saucylegs** [nununoisy/kojimabot#3]
I discovered this issue in a discord server; one person's username is "🅱🅾I" and Hideo would always greet him with "Hi 🅱 i". What happened to the 🅾? 

I suspected it was an issue with emojis being multiple bytes long, but I needed some evidence, so I did some investigation.

I went to the kojimaize.xyz website and pasted `🅱🅾I`. It returned `Hi 🅱� �i`. The space got put right in the middle of where the 🅾 was supposed to be, and the two halves were replaced by � `U+FFFD: REPLACEMENT CHARACTER` characters.

I tried figuring out what the server was *trying* to send, but even after looking at the server response as binary, it still showed the U+FFFD character. The character replacement must have been done on the server-side.

I've tried this with other text too. I've only gotten it to work with 4-byte characters, such as "🅱", "𓀄𓀅𓀆" and "🁤🁥🁦".

**Comment by nununoisy** [comment]
This may actually be an issue with compromise-syllables upstream, though I will need to test further to reproduce.

**Comment by nununoisy** [comment]
Finally fixed. Let me know if you see this behavior still.
